# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi, I'm Nicolas
tagline: Nicolas Perriault
description: >-
  ... and this is my weblog.
baseurl: "" # the subpath of your site, e.g. /blog
url:     "https://nicolas.perriault.net" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:title/
twitter_username: n1k0
github_username:  n1k0
email: nicolas@perriault.net

# Build settings
markdown: kramdown
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
highlighter: rouge
syntax_theme: monokai
paginate: 1000
plugins:
  - jekyll-feed
  - jekyll-redirect-from
feed:
  categories:
    - carnet
    - code
    - talks

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
